export const GET_ANSWERS = "GET_ANSWERS";
export const GET_ANSWERS_REQUEST = "GET_ANSWERS_REQUEST";

// export const DELETE_ANSWER = 'DELETE_ANSWER';
export const ADD_ANSWER = "ADD_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";
