export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const GET_TOP_QUESTIONS = 'GET_TOP_QUESTIONS';
export const GET_TAG_QUESTIONS = 'GET_TAG_QUESTIONS';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SET_LOADING_QUESTION = 'SET_LOADING_QUESTION';