export const GET_QUESTIONS = 'GET_QUESTIONS';
export const CREATE_QUESTION = 'CREATE_QUESTION';
export const GET_QUESTION = 'GET_QUESTION';
export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST';

// export const REMOVE_QUESTION = 'REMOVE_QUESTION';